version: "3"

networks:
  net-172.21.0.0:
    ipam:
      config:
        - subnet: 172.21.0.0/24

  net-172.21.1.0:
    ipam:
      config:
        - subnet: 172.21.1.0/24

  net-172.21.2.0:
    ipam:
      config:
        - subnet: 172.21.2.0/24

services:
  R1:
    image: rprustagi/ub22-netpkg
    container_name: R1
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - net_admin
    networks:
      net-172.21.0.0:
        ipv4_address: 172.21.0.254
      net-172.21.1.0:
        ipv4_address: 172.21.1.254
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.1.253
                      && tail -f /dev/null
                     "

  R2:
    image: rprustagi/ub22-netpkg
    container_name: R2
    tty: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - net_admin
    networks:
      net-172.21.1.0:
        ipv4_address: 172.21.1.253
      net-172.21.2.0:
        ipv4_address: 172.21.2.253
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.1.254
                      && tail -f /dev/null
                     "

  A:
    image: rprustagi/ub22-tcp-udp
    container_name: hA
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.21.0.0:
        ipv4_address: 172.21.0.5
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.0.254
                      && tail -f /dev/null
                     "

  B:
    image: rprustagi/ub22-tcp-udp
    container_name: hB
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.21.2.0:
        ipv4_address: 172.21.2.5
    command: bash -c "ip route delete default
                      && ip route add default via 172.21.2.253
                      && tail -f /dev/null
                     "

